### ISSUE TITLE
Error message stuck and incorrect

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/onboarding-web#195]
onboardingweb version: PR 188 = travis 888

When clicking "make this playground smokefree" while not being a manager the service correctly responds with a message "...is not a manager".
Instead of displaying this message the front-end locks up and displays "TypeError: Cannot read property 'data' of undefined"

**Comment by dylandejonge** [comment]
Non-managers shouldn't see this card.
Instead build filtering based on role
